"use client";

import { useRef, useMemo, useEffect, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { useTheme } from "next-themes";

// 🛑 Suppress Three.js Clock deprecation warning generated by React Three Fiber internals
if (typeof window !== "undefined") {
  const originalWarn = console.warn;
  console.warn = (...args) => {
    if (typeof args[0] === "string" && args[0].includes("THREE.Clock")) {
      return;
    }
    originalWarn(...args);
  };
}

function Particles() {
  const pointsRef = useRef<THREE.Points>(null);
  const { theme, resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  // SSR Hydration mismatch এড়াতে mounted স্টেট ট্র্যাক করা
  useEffect(() => {
    setMounted(true);
  }, []);

  const count = 500;

  const texture = useMemo(() => {
    if (typeof window === "undefined") return null;
    const canvas = document.createElement("canvas");
    canvas.width = 32;
    canvas.height = 32;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      const gradient = ctx.createRadialGradient(16, 16, 0, 16, 16, 16);
      gradient.addColorStop(0, "rgba(255,255,255,1)");
      gradient.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, 32, 32);
    }
    const tex = new THREE.CanvasTexture(canvas);
    tex.needsUpdate = true;
    return tex;
  }, []);

  useEffect(() => {
    return () => {
      texture?.dispose();
    };
  }, [texture]);

  const positions = useMemo(() => {
    const arr = new Float32Array(count * 3);
    for (let i = 0; i < count; i++) {
      arr[i * 3] = (Math.random() - 0.5) * 12;
      arr[i * 3 + 1] = (Math.random() - 0.5) * 12;
      arr[i * 3 + 2] = (Math.random() - 0.5) * 12;
    }
    return arr;
  }, []);

  useFrame((_, delta) => {
    if (pointsRef.current) {
      pointsRef.current.rotation.y += delta * 0.05;
      pointsRef.current.rotation.x += delta * 0.02;
    }
  });

  // বর্তমান থিম অনুযায়ী কালার, অপাসিটি এবং সাইজ নির্ধারণ
  const currentTheme = mounted ? (theme || resolvedTheme) : 'dark';

  const particleProps = useMemo(() => {
    if (currentTheme === "light") {
      return {
        color: "#0284c7", // লাইট মোডে স্পষ্ট ডার্ক ব্লু/অ্যাকসেন্ট
        opacity: 0.85,    // ভিজিবিলিটি বাড়ানোর জন্য অপাসিটি বাড়ানো হয়েছে
        size: 0.075,      // সাইজ সামান্য বড় করা হয়েছে
      };
    }
    if (currentTheme === "neon") {
      return {
        color: "#ff007f",
        opacity: 0.8,
        size: 0.06,
      };
    }
    // Default / Dark
    return {
      color: "#00ffc2",
      opacity: 0.6,
      size: 0.05,
    };
  }, [currentTheme]);

  return (
    <points ref={pointsRef}>
      <bufferGeometry>
        <bufferAttribute
          attach="attributes-position"
          args={[positions, 3]}
        />
      </bufferGeometry>
      <pointsMaterial
        size={particleProps.size}
        map={texture || undefined}
        color={particleProps.color}
        transparent
        opacity={particleProps.opacity}
        sizeAttenuation
        depthWrite={false}
      />
    </points>
  );
}

export default function ParticleField() {
  return (
    <div className="absolute inset-0 -z-10 pointer-events-none overflow-hidden">
      <Canvas
        camera={{ position: [0, 0, 5], fov: 75 }}
        dpr={[1, 1.5]}
        gl={{
          powerPreference: "high-performance",
          alpha: true,
          antialias: false,
        }}
      >
        <Particles />
      </Canvas>
    </div>
  );
}